sudo: required
services:
  - docker

before_install:
  - docker build -t flamchomls/docker-react -f Dockerfile.dev .

script:
  - docker run flamchomls/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-us-west-1-830795615964"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
